# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beecon < Formula
  desc "Infrastructure language your agent uses to deploy to the cloud"
  homepage "https://github.com/beeconsh/cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beeconsh/cli/releases/download/v0.2.0/beecon_darwin_amd64.tar.gz"
      sha256 "cb459b26a1efd7668c2a58c34a2fa40b212e9913fbbb98143978741579852412"

      define_method(:install) do
        bin.install "beecon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beeconsh/cli/releases/download/v0.2.0/beecon_darwin_arm64.tar.gz"
      sha256 "a49c60d47629bba5ca8a42de86c99f722d165647aef1f8b0451b9f754988cc16"

      define_method(:install) do
        bin.install "beecon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/beeconsh/cli/releases/download/v0.2.0/beecon_linux_amd64.tar.gz"
      sha256 "2fdfda25227e41a8d84cef7a872778b46678a275d40393cf34e1df1f6988e2b0"
      define_method(:install) do
        bin.install "beecon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beeconsh/cli/releases/download/v0.2.0/beecon_linux_arm64.tar.gz"
      sha256 "409a6d65436f3a69899feb6edaf62ca7819be385542c3a8d4b58f09c4d1f702f"
      define_method(:install) do
        bin.install "beecon"
      end
    end
  end

  test do
    assert_match "beecon", shell_output("#{bin}/beecon 2>&1", 1)
  end
end
